create table if not exists public.community_posts (
  id bigint generated by default as identity primary key,
  name text not null default 'Anonymous',
  city text not null default 'Canada',
  category text not null,
  message text not null,
  maple_points integer not null,
  cheers_count integer not null default 0,
  approved boolean not null default false,
  created_at timestamptz not null default now(),
  constraint community_posts_name_length check (char_length(name) between 1 and 80),
  constraint community_posts_city_length check (char_length(city) between 1 and 80),
  constraint community_posts_category check (
    category in ('Win 🎉', 'Question ❓', 'Housing 🏠', 'Jobs 💼')
  ),
  constraint community_posts_message_length check (
    char_length(message) between 1 and 300
  ),
  constraint community_posts_maple_points check (
    (category = 'Win 🎉' and maple_points = 15)
    or
    (category <> 'Win 🎉' and maple_points = 10)
  ),
  constraint community_posts_no_email check (
    (name || ' ' || city || ' ' || message)
      !~* '[[:alnum:]._%+-]+@[[:alnum:].-]+\.[[:alpha:]]{2,}'
  ),
  constraint community_posts_no_link check (
    (name || ' ' || city || ' ' || message)
      !~* '(https?://|www\.|[[:alnum:]-]+\.(com|ca|org|net|io|co|me|info|biz)(/|[[:space:]]|$))'
  ),
  constraint community_posts_no_phone check (
    (name || ' ' || city || ' ' || message)
      !~ '\+?[0-9][0-9 ()\.-]{6,}[0-9]'
  )
);

alter table public.community_posts
  add column if not exists cheers_count integer not null default 0;

create table if not exists public.community_post_cheers (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.community_posts(id) on delete cascade,
  visitor_id text not null,
  created_at timestamptz not null default now(),
  constraint community_post_cheers_visitor_id_length
    check (char_length(visitor_id) between 16 and 100),
  constraint community_post_cheers_unique unique (post_id, visitor_id)
);

create table if not exists public.community_post_rate_limits (
  id bigint generated by default as identity primary key,
  ip_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists community_post_rate_limits_lookup
  on public.community_post_rate_limits (ip_hash, created_at desc);

alter table public.community_posts enable row level security;
alter table public.community_post_cheers enable row level security;
alter table public.community_post_rate_limits enable row level security;

revoke all on table public.community_posts from anon;
revoke all on table public.community_post_cheers from anon;
revoke all on table public.community_post_rate_limits from anon;
grant select on table public.community_posts to anon;

drop policy if exists "Public can read approved community posts"
  on public.community_posts;
create policy "Public can read approved community posts"
  on public.community_posts
  for select
  to anon
  using (approved = true);

drop policy if exists "Public can submit community posts for review"
  on public.community_posts;

create or replace function public.submit_community_post(
  p_name text,
  p_city text,
  p_category text,
  p_message text,
  p_ip_hash text,
  p_honeypot text default ''
)
returns setof public.community_posts
language plpgsql
security definer
set search_path = public
as $$
declare
  clean_name text := coalesce(nullif(btrim(p_name), ''), 'Anonymous');
  clean_city text := coalesce(nullif(btrim(p_city), ''), 'Canada');
  clean_category text := btrim(coalesce(p_category, ''));
  clean_message text := btrim(coalesce(p_message, ''));
  maple_points_value integer;
begin
  if coalesce(p_honeypot, '') <> '' then
    raise exception 'Unable to submit this post.';
  end if;

  if char_length(clean_name) > 80 or char_length(clean_city) > 80 then
    raise exception 'Name and city must be 80 characters or fewer.';
  end if;

  if char_length(clean_message) < 1 or char_length(clean_message) > 300 then
    raise exception 'Message must be between 1 and 300 characters.';
  end if;

  if clean_category not in ('Win 🎉', 'Question ❓', 'Housing 🏠', 'Jobs 💼') then
    raise exception 'Please choose a valid category.';
  end if;

  if (clean_name || ' ' || clean_city || ' ' || clean_message)
    ~* '[[:alnum:]._%+-]+@[[:alnum:].-]+\.[[:alpha:]]{2,}'
    or (clean_name || ' ' || clean_city || ' ' || clean_message)
    ~* '(https?://|www\.|[[:alnum:]-]+\.(com|ca|org|net|io|co|me|info|biz)(/|[[:space:]]|$))'
    or (clean_name || ' ' || clean_city || ' ' || clean_message)
    ~ '\+?[0-9][0-9 ()\.-]{6,}[0-9]'
  then
    raise exception 'Links, email addresses, and phone numbers are not allowed.';
  end if;

  delete from public.community_post_rate_limits
  where created_at < now() - interval '1 day';

  if (
    select count(*)
    from public.community_post_rate_limits
    where ip_hash = p_ip_hash
      and created_at >= now() - interval '10 minutes'
  ) >= 3 then
    raise exception 'Too many posts. Please try again in a few minutes.';
  end if;

  if exists (
    select 1
    from public.community_posts
    where lower(regexp_replace(message, '\s+', ' ', 'g')) =
      lower(regexp_replace(clean_message, '\s+', ' ', 'g'))
      and created_at >= now() - interval '24 hours'
  ) then
    raise exception 'That message was already posted recently.';
  end if;

  maple_points_value := case when clean_category = 'Win 🎉' then 15 else 10 end;

  insert into public.community_post_rate_limits (ip_hash)
  values (p_ip_hash);

  return query
  insert into public.community_posts (
    name,
    city,
    category,
    message,
    maple_points,
    cheers_count,
    approved
  )
  values (
    clean_name,
    clean_city,
    clean_category,
    clean_message,
    maple_points_value,
    0,
    true
  )
  returning *;
end;
$$;

create or replace function public.add_maple_cheer(
  p_post_id bigint,
  p_visitor_id text
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  updated_count integer;
begin
  if char_length(coalesce(p_visitor_id, '')) < 16
    or char_length(p_visitor_id) > 100 then
    raise exception 'Invalid visitor.';
  end if;

  if not exists (
    select 1
    from public.community_posts
    where id = p_post_id and approved = true
  ) then
    raise exception 'Post not found.';
  end if;

  insert into public.community_post_cheers (post_id, visitor_id)
  values (p_post_id, p_visitor_id)
  on conflict (post_id, visitor_id) do nothing;

  if not found then
    select cheers_count into updated_count
    from public.community_posts
    where id = p_post_id;

    return updated_count;
  end if;

  update public.community_posts
  set cheers_count = cheers_count + 1
  where id = p_post_id
  returning cheers_count into updated_count;

  return updated_count;
end;
$$;

revoke all on function public.submit_community_post(
  text, text, text, text, text, text
) from public;
grant execute on function public.submit_community_post(
  text, text, text, text, text, text
) to anon;

revoke all on function public.add_maple_cheer(bigint, text) from public;
grant execute on function public.add_maple_cheer(bigint, text) to anon;
